spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:erp}
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update

admin.temp.username=${ADMIN_TEMP_USERNAME:admin@gmail.com}
admin.temp.password=${ADMIN_TEMP_PASSWORD:admin123}

spring.flyway.enabled=false
spring.devtools.livereload.enabled=true

logging.level.com.lms_erp=debug
