name: Notify MS Teams

on:
  push:
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Teams Notification
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
          notification-summary: "GitHub event triggered: ${{ github.event_name }}"
          notification-color: 17a2b8